[package]
name = "zkWASM-host-circuits"
authors = ["DelphinusLab <xgao@zoyoe.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24.1"
strum_macros = "0.24.1"
halo2_proofs = { git = "https://github.com/junyu0312/halo2", branch = "gpu", default-features = true }
halo2ecc-s = { git = "https://github.com/lanbones/halo2ecc-s.git", tag = "0.2.0" }
num-bigint = { version = "0.4", features = ["rand"] }
rand = "0.8"
ark-std = { version = "0.3.0", features = ["print-trace"] }
